IF OBJECT_ID('tempdb..#CARTEIRA_PORTO') IS NOT NULL
	DROP TABLE #CARTEIRA_PORTO;

SELECT *
	INTO #CARTEIRA_PORTO
FROM OPENQUERY(LINKEDPLAN,'
	SELECT DISTINCT*
	FROM CARTEIRA
	WHERE ID_CARTEIRA BETWEEN ''1150'' AND ''1154''');

IF OBJECT_ID('tempdb..#SAIDAS_PORTO') IS NOT NULL 
	DROP TABLE #SAIDAS_PORTO;

SELECT *
	INTO #SAIDAS_PORTO
FROM OPENQUERY(LINKEDPLAN,'
SELECT DISTINCT 
	ID_CONTR
	,NUM_CONTRATO
	,ID_CARTEIRA
	,CAST(DATA_SAIDA_EFET AS DATE) AS DATA_SAIDA_EFET
FROM CONTRATO
	WHERE ID_CARTEIRA BETWEEN ''1150'' AND ''1154''
	AND DATA_SAIDA_EFET IS NOT NULL
	AND CAST(DATA_SAIDA_EFET AS DATE) = CURRENT_DATE()');

SELECT 
	DATA_SAIDA_EFET
	,A.ID_CARTEIRA
	,B.NOME AS CARTEIRA
	,NUM_CONTRATO
	,ID_CONTR
FROM #SAIDAS_PORTO AS A JOIN #CARTEIRA_PORTO AS B ON A.ID_CARTEIRA = B.ID_CARTEIRA
ORDER BY A.ID_CARTEIRA,NUM_CONTRATO;