IF OBJECT_ID('tempdb..#CARTEIRA_PORTO') IS NOT NULL
	DROP TABLE #CARTEIRA_PORTO;

SELECT *
	INTO #CARTEIRA_PORTO
FROM OPENQUERY(LINKEDPLAN,'
	SELECT DISTINCT*
	FROM CARTEIRA
	WHERE ID_CARTEIRA BETWEEN ''1150'' AND ''1154''');

IF OBJECT_ID('tempdb..#SAIDAS_PORTO') IS NOT NULL 
	DROP TABLE #SAIDAS_PORTO;

SELECT *
	INTO #SAIDAS_PORTO
FROM OPENQUERY(LINKEDPLAN,'
SELECT DISTINCT 
	ID_CONTR
	,ID_CARTEIRA
	,CAST(DATA_SAIDA_EFET AS DATE) AS DATA_SAIDA_EFET
FROM CONTRATO
	WHERE ID_CARTEIRA BETWEEN ''1150'' AND ''1154''
	AND DATA_SAIDA_EFET IS NOT NULL
	AND YEAR(DATA_SAIDA_EFET) = YEAR(CURRENT_DATE())
	AND MONTH(DATA_SAIDA_EFET) = MONTH(CURRENT_DATE())')
SELECT 
	DATA_SAIDA_EFET
	,A.ID_CARTEIRA
	,B.NOME
	,COUNT(ID_CONTR) AS QTD_DE_ENTRADAS
FROM #SAIDAS_PORTO AS A JOIN #CARTEIRA_PORTO AS B ON A.ID_CARTEIRA = B.ID_CARTEIRA

GROUP BY 
	DATA_SAIDA_EFET
	,A.ID_CARTEIRA
	,B.NOME
ORDER BY DATA_SAIDA_EFET